name: build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.6'
    - name: Build
      run: |
        go mod download
        go build -o event2stdin
    - name: Deploy to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: event2stdin
        asset_name: event2stdin
        asset_content_type: application/octet-stream